### ISSUE TITLE
Flamegraph way too short in `wall` mode

### ISSUE THREAD

**Issue by matt17r** [tmm1/stackprof#193]
While using rack-mini-profiler (RMP) to debug some performance issues I was regularly seeing a flamegraph profile only 30ms long despite the request taking 2000-4000ms. With some help from Nate Berkopec, I eventually confirmed the flamegraph profiles were too short which helped me find some other people [reporting a similar issue in the RMP repo](https://github.com/MiniProfiler/rack-mini-profiler/issues/536).

One [comment](https://github.com/MiniProfiler/rack-mini-profiler/issues/536#issuecomment-1221466107) suggested the problem is with StackProf (and their workaround of setting the mode to `object` instead of `wall` worked for me).

I'm not sure if this is a configuration issue in RMP, a problem with StackProf, bad assumptions on my part or something else entirely but I'd be keen to understand it more and maybe help prevent the problem slowing down others who are just getting started with performance troubleshooting.

I've checked Ruby and all my gems are up to date:

- ruby 3.1.3p185
- rails (7.0.3.1)
- rack-mini-profiler (3.0.0)
- stackprof (0.2.23)

In case it helps, I have also attached the [two flamegraph profiles](https://github.com/tmm1/stackprof/files/10205249/Flamegraph.profiles.zip).

**Comment by tenderlove** [comment]
@matt17r can you try with the latest version? `0.2.23`

It looks like all of the reports are related to using threads, and I think 0.2.23 may have addressed the issue.

**Comment by tenderlove** [comment]
btw, you probably *don't* want object mode as object mode is only telling you where objects are being allocated, not where time is being spent (unless you're really interested in object allocations vs time spent.  That said, eliminating object allocations is usually a good thing 😅)

**Comment by matt17r** [comment]
Thanks for the tip about object mode, as you can probably tell I'm still learning about profiling...

I was originally seeing this with `0.2.22` but I updated to `0.2.23` and tested that before opening this issue so that doesn't seem to have helped me.

Is there anything else I can try or any additional logging I can generate to try and narrow in on what's going on?

**Comment by AnomalousBit** [comment]
> btw, you probably _don't_ want object mode as object mode is only telling you where objects are being allocated, not where time is being spent (unless you're really interested in object allocations vs time spent. That said, eliminating object allocations is usually a good thing sweat_smile)

Maybe I'm understanding this wrong, but `:object` mode uses the `RUBY_INTERNAL_EVENT_NEWOBJ` event to trigger the stackprof statistics collection (which is a snapshot of the currently executing stack trace). It's just pausing the stats collector every time an object is created instead of just using a cpu-cycle count or wall-clock based interrupt. The same statistics are generated by looking at the currently executing stack trace, just at a different interval (think, more slices of cheese from the same cheese block). :object mode is completely aware of how much time it spent in between interrupts (as are the other modes).

More simply put, more statistics collecting interrupts = a more detailed and accurate flamegraph.

I know that it's highly code dependent, but in my experience I get far more interrupts using :object mode than when I use the default intervals in :cpu and :wall methods. I suppose :object would be a really poor method of polling if you somehow managed to create very few objects or if you're calling out to a lot of non-ruby / libffi code?

I'm sorry if I sound pedantic, I'm just trying to better understand and learn. I tried to triage and fix the (threading?) issue over on rack-mini-profiler (https://github.com/MiniProfiler/rack-mini-profiler/issues/536). My best guess at the time was that :object mode was somehow seeing the current thread and it's real stack trace, where as :wall was only getting a stack trace from the initial thread (I think in my case it was always showing the puma or rails thread and not the thread currently executing). I haven't been able to reproduce this using the stackprof gem alone outside of rack-mini-profiler.

Thanks for all of your help and amazing commit(ment)s @tenderlove

**Comment by matt17r** [comment]
I [could not reproduce this issue in a structurally equivalent demo app](https://github.com/MiniProfiler/rack-mini-profiler/issues/536#issuecomment-1416784056) so I'm going to chalk my problems up to coincidence and close this issue.

If anyone sees a related issue using stackprof 0.2.23 or greater feel free to comment on this issue (or open a new one and ping me).
